'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '@/lib/client-api';
type Item = { id: string; email?: string; banned?: boolean; wallet?: { balance: number; reserved: number }; suffix?: string; status?: string; batch?: { credits: number; expiresAt: string | null }; delta?: number; reason?: string; action?: string; actorId?: string; targetId?: string; detail?: object };
export default function Admin() {
  const [allowed, setAllowed] = useState(false); const [kind, setKind] = useState('users'); const [page, setPage] = useState(0); const [filter, setFilter] = useState(''); const [status, setStatus] = useState(''); const [items, setItems] = useState<Item[]>([]);
  const [count, setCount] = useState(10); const [credits, setCredits] = useState(10); const [expiry, setExpiry] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [codes, setCodes] = useState<string[]>([]); const [batchId, setBatchId] = useState(''); const [generatedCredits, setGeneratedCredits] = useState(0); const [target, setTarget] = useState(''); const [delta, setDelta] = useState(10); const [reason, setReason] = useState('');
  const load = useCallback(async () => { try { const params = new URLSearchParams({ kind, page: String(page), email: filter, userId: target, status }); setItems((await api(`/api/admin?${params}`)).items); } catch (error) { setMessage(error instanceof Error ? error.message : '加载失败'); } }, [kind, page, filter, target, status]);
  useEffect(() => { api('/api/me').then(profile => { if (profile.user.role === 'ADMIN') setAllowed(true); else setMessage('需要管理员权限'); }).catch(error => setMessage(error.message)); }, []);
  useEffect(() => { if (allowed) void load(); }, [allowed, load]);
  async function act(body: object) { setBusy(true); setMessage(''); try { const result = await api('/api/admin', body); setMessage('操作成功'); await load(); return result; } catch (error) { setMessage(error instanceof Error ? error.message : '操作失败'); } finally { setBusy(false); } }
  async function generate(e: FormEvent) { e.preventDefault(); const result = await act({ action: 'cards', count, credits, expiresAt: expiry ? new Date(expiry).toISOString() : null }); if (result) { setCodes(result.codes); setBatchId(result.batchId); setGeneratedCredits(result.credits); } }
  function saveCodes() { const url = URL.createObjectURL(new Blob(['card,credits,batch\n' + codes.map(code => `${code},${generatedCredits},${batchId}`).join('\n')], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `cards-${batchId}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  const inputClass = 'rounded border p-2 dark:bg-neutral-900';
  return <main className="mx-auto max-w-5xl space-y-8 px-5 py-10"><h1 className="text-2xl font-bold">管理后台</h1><p role="status">{message}</p>{allowed && <>
    <section><h2 className="mb-3 text-lg font-semibold">批量制卡</h2><form className="flex flex-wrap items-end gap-3" onSubmit={generate}><label>数量<input className={`${inputClass} block w-24`} type="number" min={1} max={500} required value={count} onChange={e => setCount(Number(e.target.value))} /></label><label>每张次数<input className={`${inputClass} block w-24`} type="number" min={1} max={100000} required value={credits} onChange={e => setCredits(Number(e.target.value))} /></label><label>兑换截止（留空长期有效）<input className={`${inputClass} block`} type="datetime-local" value={expiry} onChange={e => setExpiry(e.target.value)} /></label><button disabled={busy || codes.length > 0} className="rounded bg-neutral-700 p-3 text-white disabled:opacity-50">生成卡密</button></form>{codes.length > 0 && <div className="mt-4 rounded bg-neutral-900 p-4 text-neutral-100"><p>明文卡密仅在本次生成后可见，请立即下载保存。</p><button className="mr-4 underline" onClick={saveCodes}>下载卡密 CSV</button><button onClick={() => setCodes([])}>已保存，清除本页明文</button></div>}</section>
    <section><h2 className="mb-3 text-lg font-semibold">用户与卡密</h2><div className="flex flex-wrap gap-3"><select aria-label="记录类型" className={inputClass} value={kind} onChange={e => { setKind(e.target.value); setPage(0); }}><option value="users">用户</option><option value="cards">卡密</option><option value="ledger">所选用户流水</option><option value="audit">管理操作日志</option></select>{kind === 'users' && <input className={inputClass} placeholder="按邮箱查找" value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }} />}{kind === 'cards' && <select aria-label="卡密状态" className={inputClass} value={status} onChange={e => { setStatus(e.target.value); setPage(0); }}><option value="">全部状态</option><option value="UNUSED">未兑换</option><option value="REDEEMED">已兑换</option><option value="DISABLED">已禁用</option></select>}<button onClick={load}>刷新</button></div><div className="mt-4 space-y-3">{items.map(item => <div key={item.id} className="flex flex-wrap items-center gap-4 rounded border p-3">{item.email ? <><span>{item.email} · 可用 {(item.wallet?.balance || 0) - (item.wallet?.reserved || 0)} · {item.banned ? '已封禁' : '正常'}</span><button className="text-neutral-300" onClick={() => setTarget(item.id)}>选择用户</button><button disabled={busy || !reason.trim()} onClick={() => act({ action: 'ban', userId: item.id, banned: !item.banned, reason })}>{item.banned ? '解除封禁' : '封禁'}（需原因）</button></> : item.suffix ? <><span>尾号 {item.suffix} · {item.batch?.credits} 次 · {item.status} · 截止 {item.batch?.expiresAt ? new Date(item.batch.expiresAt).toLocaleString('zh-CN') : '长期有效'}</span>{item.status === 'UNUSED' && <button disabled={busy} onClick={() => act({ action: 'disable', cardId: item.id })}>禁用</button>}</> : <pre className="max-w-full overflow-auto text-xs">{JSON.stringify(item, null, 2)}</pre>}</div>)}</div><div className="mt-4 flex gap-4"><button disabled={page === 0} onClick={() => setPage(page - 1)}>上一页</button><span>第 {page + 1} 页</span><button disabled={items.length < 50} onClick={() => setPage(page + 1)}>下一页</button></div></section>
    <section><h2 className="mb-3 text-lg font-semibold">人工调账 / 封禁原因</h2><form className="flex flex-wrap gap-3" onSubmit={e => { e.preventDefault(); void act({ action: 'adjust', userId: target, delta, reason }); }}><input aria-label="用户 ID" required placeholder="先选择用户" className={inputClass} value={target} onChange={e => setTarget(e.target.value)} /><input aria-label="调账次数" required className={`${inputClass} w-24`} type="number" min={-100000} max={100000} value={delta} onChange={e => setDelta(Number(e.target.value))} /><input aria-label="操作原因" required maxLength={300} className={inputClass} placeholder="填写操作原因" value={reason} onChange={e => setReason(e.target.value)} /><button disabled={busy} className="rounded bg-neutral-700 p-3 text-white">提交调账</button></form></section>
    <section><h2 className="mb-3 text-lg font-semibold">异常导出恢复</h2><p className="mb-3 text-sm">释放超过 10 分钟仍未完成的任务预占额度，每次最多 100 条。</p><button disabled={busy} onClick={() => act({ action: 'recover' })}>恢复超时任务</button></section>
  </>}</main>;
}
